# Builds a .deb for MADlib via debuild/debhelper (see debian/), replacing
# the CPack DEB generator. Usage:
#   make -f deb.mk pkg-deb                # Greengage 6 (default)
#   GREENGAGE_VERSION=7 make -f deb.mk pkg-deb
#
# GREENGAGE_VERSION drives both the package name (greengage6-madlib /
# greengage7-madlib, see debian/control.in) and the build (GPHOME/pg_config
# lookup in debian/rules) - it is the single knob for targeting a Greengage
# major version.

SHELL := /bin/bash

GREENGAGE_VERSION ?= 6
MAINTAINER := Apache MADlib <dev@madlib.apache.org>

# Version resolution, first match wins:
#   1. MADLIB_PACKAGE_VERSION=X.Y.Z - explicit override (release automation)
#   2. git describe --tags --abbrev=0 - normal checkout (nearest tag)
#   3. .version                       - git-archive substitution for source
#                                        tarballs (see .gitattributes)
#   4. VERSION                        - file generated by `make VERSION`
#                                        (Docker build stage, .git absent)
#   5. src/config/Version.yml         - final fallback for untagged checkouts
RAW_VERSION := $(or $(MADLIB_PACKAGE_VERSION),$(shell git describe --tags --abbrev=0 2>/dev/null),$(shell grep -v '\$$Format:' .version 2>/dev/null),$(shell cat VERSION 2>/dev/null),$(shell sed -n 's/^version:[ \t]*//p' src/config/Version.yml 2>/dev/null))
GIT_VERSION := $(shell echo '$(RAW_VERSION)' | sed 's/^[^0-9]*//')

ifeq ($(strip $(GIT_VERSION)),)
$(error version unknown - pass MADLIB_PACKAGE_VERSION=X.Y.Z, or build from a git checkout with tags)
endif

PACKAGE_NAME    := greengage$(GREENGAGE_VERSION)-madlib
DATE_RFC        := $(shell date -R)
DISTRO_CODENAME := $(shell lsb_release -sc 2>/dev/null || echo unstable)
DEB_TOPDIR      ?= $(CURDIR)/../deb-packages

# Generate for Dockerfile where .git is absent
VERSION :
	@echo "Update $@"
	@echo "$(GIT_VERSION)" > $@
	@cat $@

debian/control: debian/control.in
	@sed 's/@GREENGAGE_VERSION@/$(GREENGAGE_VERSION)/g' $< > $@

debian/changelog:
	@echo "$(PACKAGE_NAME) ($(GIT_VERSION)) $(DISTRO_CODENAME); urgency=medium" > $@
	@echo "" >> $@
	@echo "  * $(GIT_VERSION) build" >> $@
	@echo "" >> $@
	@echo " -- $(MAINTAINER)  $(DATE_RFC)" >> $@

# Default packaging target
pkg : pkg-info pkg-deb

# Display package info
pkg-info :
	@echo "PACKAGE_NAME: $(PACKAGE_NAME)"
	@echo "GREENGAGE_VERSION: $(GREENGAGE_VERSION)"
	@echo "MAINTAINER: $(MAINTAINER)"
	@echo "GIT_VERSION: $(GIT_VERSION)"
	@echo "DISTRO_CODENAME: $(DISTRO_CODENAME)"

# Build Debian package (binary-only, unsigned)
pkg-deb : debian/control debian/changelog
	@GREENGAGE_VERSION="$(GREENGAGE_VERSION)" debuild --preserve-env -us -uc -b
	@mkdir -p $(DEB_TOPDIR)
	@find $(CURDIR)/../ -maxdepth 1 -type f \( -name "*.deb" \
											-o -name "*.buildinfo" \
											-o -name "*.changes" \) \
											-exec mv -f {} $(DEB_TOPDIR)/ \;

.PHONY: VERSION debian/control debian/changelog pkg pkg-info pkg-deb clean-pkg

clean-pkg :
	rm -f debian/control debian/changelog VERSION
