# .github/workflows/release.yml
name: GreengageDB madlib Release

on:
  release:
    types: [released]

jobs:
  upload-to-release:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target_os: ubuntu
          target_os_version: '22.04'
          greengage_version: '6'
          extensions: 'deb ddeb'
        - target_os: ubuntu
          target_os_version: '24.04'
          greengage_version: '6'
          extensions: 'deb ddeb'
        # - target_os: ubuntu
        #   target_os_version: '22.04'
        #   greengage_version: '7'
        #   extensions: 'deb ddeb'
        # - target_os: ubuntu
        #   target_os_version: '24.04'
        #   greengage_version: '7'
        #   extensions: 'deb ddeb'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read
    steps:
      - name: Upload packages to release
        uses: greengagedb/greengage-ci/.github/actions/upload-pkgs-to-release@v45
        with:
          workflow_for_waiting: Build and Package DEB
          target_os:            ${{ matrix.target_os }}
          target_os_version:    ${{ matrix.target_os_version }}
          extensions:           ${{ matrix.extensions }}
          artifact_prefix:      deb-packages-madlib${{ matrix.greengage_version }}
